#!/usr/bin/env python3
"""Generate frozen oracle data for SciPP tests from the reference SciPy.

Outputs (committed so CI runs without Python):
  tests/golden/golden.hpp        - input/expected vectors for special + constants
  src/constants/codata_table.inc - CODATA physical_constants table entries

Run:  python3 tests/oracle/generate.py
Refresh after touching the test set; review the diff before committing.
"""
import os
import numpy as np
import scipy.special as sps
import scipy.constants as spc
import scipy.linalg as sla
import scipy.fft as spf
import scipy.optimize as spo
import scipy.integrate as spi
import scipy.interpolate as spn
import scipy.stats as sst
import scipy.signal as ssg
import scipy.sparse as ssp
import scipy.sparse.linalg as sspl
import scipy.sparse.csgraph as sscg
from scipy.spatial import KDTree, ConvexHull, Delaunay, distance as spd
from scipy.spatial.transform import Rotation as spR, Slerp as spSlerp
import scipy.ndimage as sni
import scipy.cluster.vq as scv
import scipy.cluster.hierarchy as sch
from scipy.io import mmread, mmwrite, wavfile
import io as _io

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
GOLDEN = os.path.join(ROOT, "tests", "golden", "golden.hpp")
CODATA = os.path.join(ROOT, "src", "constants", "codata_table.inc")


def fmt(v):
    v = float(v)
    if np.isnan(v):
        return 'std::nan("")'
    if np.isinf(v):
        return "INFINITY" if v > 0 else "-INFINITY"
    return repr(v)


def emit_arr(out, name, xs, fn):
    ys = [fn(x) for x in xs]
    out.append(f"inline const double {name}_in[] = {{{', '.join(fmt(x) for x in xs)}}};")
    out.append(f"inline const double {name}_out[] = {{{', '.join(fmt(y) for y in ys)}}};")
    out.append(f"inline constexpr int {name}_n = {len(xs)};")


def emit_scalar(out, name, value):
    out.append(f"inline const double {name} = {fmt(value)};")


def emit_mat(out, name, m):
    """Emit a 2-D array (row-major) plus its dimensions."""
    m = np.asarray(m, dtype=float)
    r, c = (m.shape + (1,))[:2] if m.ndim == 2 else (m.shape[0], 1)
    flat = m.ravel()
    out.append(f"inline const double {name}_d[] = {{{', '.join(fmt(v) for v in flat)}}};")
    out.append(f"inline constexpr int {name}_r = {m.shape[0]};")
    out.append(f"inline constexpr int {name}_c = {m.shape[1] if m.ndim == 2 else 1};")


def main():
    out = ["#pragma once", "// AUTO-GENERATED by tests/oracle/generate.py from SciPy. Do not edit.",
           "#include <cmath>", "namespace golden {"]

    # ---- gamma family ----
    emit_arr(out, "gamma", [0.5, 1.0, 1.5, 2.5, 5.0, 10.0, -0.5, -1.5], sps.gamma)
    emit_arr(out, "gammaln", [0.5, 1.5, 2.5, 5.0, 10.0, 100.0], sps.gammaln)
    emit_arr(out, "digamma", [0.1, 0.5, 1.0, 2.0, 5.0, 10.0], sps.digamma)
    emit_arr(out, "polygamma1", [0.5, 1.0, 2.0, 5.0], lambda x: sps.polygamma(1, x))
    emit_arr(out, "polygamma2", [0.5, 1.0, 2.0, 5.0], lambda x: sps.polygamma(2, x))
    emit_scalar(out, "beta_2_3", sps.beta(2, 3))
    emit_scalar(out, "beta_05_25", sps.beta(0.5, 2.5))
    emit_scalar(out, "betaln_2_3", sps.betaln(2, 3))
    emit_scalar(out, "betaln_10_20", sps.betaln(10, 20))

    # ---- error functions ----
    emit_arr(out, "erf", [-2, -1, -0.5, 0, 0.5, 1, 2, 3], sps.erf)
    emit_arr(out, "erfc", [-2, -1, -0.5, 0, 0.5, 1, 2, 3], sps.erfc)
    emit_arr(out, "erfinv", [-0.9, -0.5, 0.0, 0.5, 0.9, 0.99], sps.erfinv)
    emit_arr(out, "erfcinv", [0.1, 0.5, 1.0, 1.5, 1.9], sps.erfcinv)

    # ---- exponential integrals ----
    emit_arr(out, "exp1", [0.1, 0.5, 1.0, 2.0, 5.0, 10.0], sps.exp1)
    emit_arr(out, "expi", [0.1, 0.5, 1.0, 2.0, 5.0], sps.expi)
    emit_arr(out, "expn2", [0.1, 0.5, 1.0, 2.0, 5.0], lambda x: sps.expn(2, x))
    emit_arr(out, "exprel", [-1.0, -0.001, 0.0, 0.001, 1.0, 5.0], sps.exprel)

    # ---- Bessel ----
    bx = [0.5, 1.0, 2.0, 5.0, 10.0]
    emit_arr(out, "jv0", bx, lambda x: sps.jv(0, x))
    emit_arr(out, "jv1", bx, lambda x: sps.jv(1, x))
    emit_arr(out, "jvhalf", bx, lambda x: sps.jv(0.5, x))
    emit_arr(out, "yv0", bx, lambda x: sps.yv(0, x))
    emit_arr(out, "yv1", bx, lambda x: sps.yv(1, x))
    emit_arr(out, "iv0", bx, lambda x: sps.iv(0, x))
    emit_arr(out, "iv1", bx, lambda x: sps.iv(1, x))
    emit_arr(out, "kv0", bx, lambda x: sps.kv(0, x))
    emit_arr(out, "kv1", bx, lambda x: sps.kv(1, x))
    emit_arr(out, "i0", bx, sps.i0)
    emit_arr(out, "i1", bx, sps.i1)
    emit_arr(out, "k0", bx, sps.k0)
    emit_arr(out, "k1", bx, sps.k1)

    # ---- orthogonal evaluators ----
    ox = [-1.0, -0.5, 0.0, 0.3, 0.7, 1.0]
    emit_arr(out, "legendre3", ox, lambda x: sps.eval_legendre(3, x))
    emit_arr(out, "legendre10", ox, lambda x: sps.eval_legendre(10, x))
    emit_arr(out, "chebyt4", ox, lambda x: sps.eval_chebyt(4, x))
    emit_arr(out, "chebyt7", ox, lambda x: sps.eval_chebyt(7, x))
    emit_arr(out, "hermite3", [-2.0, -1.0, 0.0, 0.5, 1.0, 2.0], lambda x: sps.eval_hermite(3, x))
    emit_arr(out, "laguerre3", [0.0, 0.5, 1.0, 2.0, 5.0], lambda x: sps.eval_laguerre(3, x))
    emit_arr(out, "genlag3", [0.0, 0.5, 1.0, 2.0, 5.0],
             lambda x: sps.eval_genlaguerre(3, 1.5, x))

    # ---- combinatorics ----
    emit_scalar(out, "comb_10_3", sps.comb(10, 3))
    emit_scalar(out, "comb_52_5", sps.comb(52, 5))
    emit_scalar(out, "perm_10_3", sps.perm(10, 3))
    emit_scalar(out, "fact_5", sps.factorial(5))
    emit_scalar(out, "fact_10", sps.factorial(10))

    # ---- reductions ----
    a1 = np.array([1.0, 2.0, 3.0, 4.0])
    emit_scalar(out, "lse_a1", sps.logsumexp(a1))
    sm = sps.softmax(a1)
    out.append(f"inline const double softmax_a1[] = {{{', '.join(fmt(v) for v in sm)}}};")
    big = np.array([1000.0, 1001.0, 1002.0])
    emit_scalar(out, "lse_big", sps.logsumexp(big))
    a2 = np.array([[1.0, 2.0, 3.0], [4.0, 6.0, 8.0]])
    lse_ax1 = sps.logsumexp(a2, axis=1)
    out.append(f"inline const double lse_a2_ax1[] = {{{', '.join(fmt(v) for v in lse_ax1)}}};")
    sm_ax1 = sps.softmax(a2, axis=1).ravel()
    out.append(f"inline const double softmax_a2_ax1[] = {{{', '.join(fmt(v) for v in sm_ax1)}}};")

    # ---- constants (stable / definition-based) ----
    for nm, val in [("c", spc.c), ("h", spc.h), ("hbar", spc.hbar), ("e", spc.e),
                    ("k", spc.k), ("N_A", spc.N_A), ("R", spc.R), ("g", spc.g),
                    ("pi", spc.pi), ("atm", spc.atm), ("bar", spc.bar),
                    ("inch", spc.inch), ("hour", spc.hour), ("eV", spc.eV)]:
        emit_scalar(out, f"const_{nm}", val)

    # physical_constants lookups under test
    for key, cname in [("electron mass", "electron_mass"),
                       ("proton mass", "proton_mass"),
                       ("Boltzmann constant", "boltzmann")]:
        v, u, unc = spc.physical_constants[key]
        emit_scalar(out, f"pc_{cname}_value", v)
        emit_scalar(out, f"pc_{cname}_prec", spc.precision(key))

    # temperature + wavelength conversions
    emit_scalar(out, "temp_c2f_100", spc.convert_temperature(100.0, "Celsius", "Fahrenheit"))
    emit_scalar(out, "temp_k2c_300", spc.convert_temperature(300.0, "Kelvin", "Celsius"))
    emit_scalar(out, "l2nu_500nm", spc.lambda2nu(500e-9))

    # ---- linalg ----
    Asq = np.array([[4., 3., 2., 1.], [3., 5., 1., 2.], [2., 1., 6., 3.], [1., 2., 3., 7.]])
    Aspd = np.array([[4., 1., 1.], [1., 3., 0.], [1., 0., 2.]])
    Atall = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 10.], [1., 0., 1.], [2., 1., 0.]])
    b4 = np.array([1., 2., 3., 4.])
    b5 = np.array([1., 2., 3., 4., 5.])
    emit_mat(out, "la_Asq", Asq)
    emit_mat(out, "la_Aspd", Aspd)
    emit_mat(out, "la_Atall", Atall)
    emit_mat(out, "la_b4", b4.reshape(-1, 1))
    emit_mat(out, "la_b5", b5.reshape(-1, 1))

    emit_scalar(out, "la_det_Asq", sla.det(Asq))
    emit_mat(out, "la_inv_Asq", sla.inv(Asq))
    emit_mat(out, "la_solve_Asq_b4", sla.solve(Asq, b4).reshape(-1, 1))
    emit_mat(out, "la_lstsq_x", sla.lstsq(Atall, b5)[0].reshape(-1, 1))
    emit_mat(out, "la_pinv_Atall", sla.pinv(Atall))
    emit_mat(out, "la_pinvh_Aspd", sla.pinvh(Aspd))
    emit_mat(out, "la_eigvalsh_Aspd", sla.eigvalsh(Aspd).reshape(-1, 1))
    emit_scalar(out, "la_norm_fro", sla.norm(Asq))
    emit_scalar(out, "la_norm_1", sla.norm(Asq, 1))
    emit_scalar(out, "la_norm_inf", sla.norm(Asq, np.inf))
    emit_mat(out, "la_chol_upper", sla.cholesky(Aspd))           # upper default
    emit_mat(out, "la_expm_Asq", sla.expm(Asq))
    emit_mat(out, "la_expm_rot", sla.expm(np.array([[0., 1.], [-1., 0.]])))
    pu, pp = sla.polar(Asq)
    emit_mat(out, "la_polar_u", pu)
    emit_mat(out, "la_polar_p", pp)

    # special matrices
    emit_mat(out, "la_toeplitz", sla.toeplitz([1., 2., 3., 4.]))
    emit_mat(out, "la_circulant", sla.circulant([1., 2., 3.]))
    emit_mat(out, "la_hankel", sla.hankel([1., 2., 3.], [3., 4., 5.]))
    emit_mat(out, "la_hilbert", sla.hilbert(4))
    emit_mat(out, "la_hadamard", sla.hadamard(4))
    emit_mat(out, "la_pascal", sla.pascal(4))
    emit_mat(out, "la_companion", sla.companion([1., -6., 11., -6.]))
    emit_mat(out, "la_tri", np.tril(np.ones((4, 4))))
    emit_mat(out, "la_leslie", sla.leslie([0.1, 2.0, 1.0, 0.1], [0.2, 0.8, 0.7]))
    emit_mat(out, "la_blockdiag", sla.block_diag(np.array([[1., 2.], [3., 4.]]),
                                                 np.array([[5.]]), np.array([[6., 7.]])))

    # ---- fft ----
    def emit_vec(name, arr):
        arr = np.asarray(arr, dtype=float).ravel()
        out.append(f"inline const double {name}[] = {{{', '.join(fmt(v) for v in arr)}}};")
        out.append(f"inline constexpr int {name}_n = {len(arr)};")

    xr = np.array([1., 2., 3., 4., 5., 6., 7., 8.])
    emit_vec("fft_x", xr)
    F = spf.fft(xr)
    emit_vec("fft_re", F.real)
    emit_vec("fft_im", F.imag)
    Rf = spf.rfft(xr)
    emit_vec("rfft_re", Rf.real)
    emit_vec("rfft_im", Rf.imag)
    Fo = spf.fft(xr, norm="ortho")
    emit_vec("fft_ortho_re", Fo.real)
    emit_vec("fft_ortho_im", Fo.imag)

    for t in (1, 2, 3, 4):
        emit_vec(f"dct{t}", spf.dct(xr, type=t))
        emit_vec(f"dst{t}", spf.dst(xr, type=t))
        emit_vec(f"idct{t}", spf.idct(xr, type=t))
        emit_vec(f"idst{t}", spf.idst(xr, type=t))

    # DCT/DST under norm="ortho" and norm="forward", all four types.
    for t in (1, 2, 3, 4):
        emit_vec(f"dct{t}_ortho", spf.dct(xr, type=t, norm="ortho"))
        emit_vec(f"dst{t}_ortho", spf.dst(xr, type=t, norm="ortho"))
        emit_vec(f"dct{t}_fwd", spf.dct(xr, type=t, norm="forward"))
        emit_vec(f"dst{t}_fwd", spf.dst(xr, type=t, norm="forward"))
        emit_vec(f"idct{t}_ortho", spf.idct(xr, type=t, norm="ortho"))
        emit_vec(f"idst{t}_ortho", spf.idst(xr, type=t, norm="ortho"))
        emit_vec(f"idct{t}_fwd", spf.idct(xr, type=t, norm="forward"))
        emit_vec(f"idst{t}_fwd", spf.idst(xr, type=t, norm="forward"))

    # dct along axis=0 of a 2-D array
    X2 = np.array([[1., 2., 3.], [4., 5., 6.]])
    emit_mat(out, "fft_X2", X2)
    emit_mat(out, "fft_dct2_ax0", spf.dct(X2, type=2, axis=0))

    # dctn/dstn over both axes of a 2-D array (default + ortho).
    X3 = np.array([[1., 2., 3., 4.], [5., 6., 7., 8.], [9., 10., 11., 12.]])
    emit_mat(out, "fft_X3", X3)
    emit_mat(out, "fft_dctn2", spf.dctn(X3, type=2))
    emit_mat(out, "fft_dctn2_ortho", spf.dctn(X3, type=2, norm="ortho"))
    emit_mat(out, "fft_dstn3", spf.dstn(X3, type=3))

    emit_vec("fftfreq8", spf.fftfreq(8, 0.1))
    emit_vec("rfftfreq8", spf.rfftfreq(8, 0.1))
    emit_vec("fftshift8", spf.fftshift(np.arange(8.0)))
    for n in (1, 7, 8, 13, 100, 1000):
        emit_scalar(out, f"nfl_{n}", float(spf.next_fast_len(n)))

    # ---- optimize ----
    emit_scalar(out, "opt_brentq", spo.brentq(lambda x: x * x - 2.0, 0.0, 2.0))
    emit_scalar(out, "opt_bisect", spo.bisect(lambda x: x * x - 2.0, 0.0, 2.0))
    emit_scalar(out, "opt_newton", spo.newton(lambda x: x**3 - 2 * x - 5, 2.0))

    msb = spo.minimize_scalar(lambda x: np.cosh(x - 1.7), method="brent")
    emit_scalar(out, "opt_ms_brent_x", msb.x)
    emit_scalar(out, "opt_ms_brent_f", msb.fun)
    msd = spo.minimize_scalar(lambda x: (x - 2.0) ** 2, method="bounded", bounds=(0.0, 1.0))
    emit_scalar(out, "opt_ms_bounded_x", msd.x)

    def rosen(p):
        return (1 - p[0]) ** 2 + 100.0 * (p[1] - p[0] ** 2) ** 2
    nm = spo.minimize(rosen, [-1.2, 1.0], method="Nelder-Mead")
    emit_mat(out, "opt_nm_rosen", np.asarray(nm.x).reshape(-1, 1))

    quad = lambda p: (p[0] - 3.0) ** 2 + (p[1] + 1.0) ** 2
    bf = spo.minimize(quad, [0.0, 0.0], method="BFGS")
    emit_mat(out, "opt_bfgs_quad", np.asarray(bf.x).reshape(-1, 1))

    # additional minimize methods: Powell, CG, L-BFGS-B (Rosenbrock + shifted quadratic)
    for tag, meth in [("powell", "Powell"), ("cg", "CG"), ("lbfgsb", "L-BFGS-B")]:
        rr = spo.minimize(rosen, [-1.2, 1.0], method=meth)
        emit_mat(out, f"opt_{tag}_rosen", np.asarray(rr.x).reshape(-1, 1))
        emit_scalar(out, f"opt_{tag}_rosen_f", rr.fun)
        qr = spo.minimize(quad, [0.0, 0.0], method=meth)
        emit_mat(out, f"opt_{tag}_quad", np.asarray(qr.x).reshape(-1, 1))
        emit_scalar(out, f"opt_{tag}_quad_f", qr.fun)
    # L-BFGS-B with box bounds whose interior excludes the unconstrained min (3, -1)
    br = spo.minimize(quad, [0.0, 0.0], method="L-BFGS-B", bounds=[(0.0, 2.0), (0.0, 5.0)])
    emit_mat(out, "opt_lbfgsb_bnd", np.asarray(br.x).reshape(-1, 1))
    emit_scalar(out, "opt_lbfgsb_bnd_f", br.fun)

    # curve_fit: a*exp(-b*x)+c, noise-free
    cf_x = np.linspace(0.0, 4.0, 20)
    cf_true = np.array([2.5, 1.3, 0.5])
    cf_y = cf_true[0] * np.exp(-cf_true[1] * cf_x) + cf_true[2]
    emit_vec("cf_xdata", cf_x)
    emit_vec("cf_ydata", cf_y)
    emit_mat(out, "opt_curvefit_true", cf_true.reshape(-1, 1))
    popt, _ = spo.curve_fit(lambda x, a, b, c: a * np.exp(-b * x) + c, cf_x, cf_y, p0=[1., 1., 1.])
    emit_mat(out, "opt_curvefit_popt", np.asarray(popt).reshape(-1, 1))

    # fsolve: x^2+y^2-4=0, x-y=0  -> (sqrt2, sqrt2)
    fs = spo.fsolve(lambda v: [v[0] ** 2 + v[1] ** 2 - 4.0, v[0] - v[1]], [1.0, 1.0])
    emit_mat(out, "opt_fsolve", np.asarray(fs).reshape(-1, 1))

    # ---- integrate ----
    # fixed-sample quadrature on an odd-length grid (even #intervals)
    ig_x = np.linspace(0.0, np.pi, 21)
    ig_y = np.sin(ig_x)
    emit_vec("ig_x", ig_x)
    emit_vec("ig_y", ig_y)
    emit_scalar(out, "ig_trapz", spi.trapezoid(ig_y, ig_x))
    emit_scalar(out, "ig_simpson", spi.simpson(ig_y, x=ig_x))
    emit_vec("ig_cumtrapz", spi.cumulative_trapezoid(ig_y, ig_x, initial=0.0))
    # adaptive quad: ∫_0^1 4/(1+x^2) dx = pi ; ∫_0^2 x^3 dx = 4
    emit_scalar(out, "ig_quad_pi", spi.quad(lambda x: 4.0 / (1.0 + x * x), 0.0, 1.0)[0])
    emit_scalar(out, "ig_quad_exp", spi.quad(lambda x: np.exp(-x * x), 0.0, 2.0)[0])
    emit_scalar(out, "ig_fixed_quad", spi.fixed_quad(lambda x: x**3, 0.0, 2.0, n=5)[0])

    # ---- interpolate ----
    ip_x = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
    ip_y = np.sin(ip_x)
    ip_q = np.linspace(0.2, 4.8, 12)
    emit_vec("ip_x", ip_x)
    emit_vec("ip_y", ip_y)
    emit_vec("ip_q", ip_q)
    emit_vec("ip_linear", spn.interp1d(ip_x, ip_y, kind="linear")(ip_q))
    emit_vec("ip_nearest", spn.interp1d(ip_x, ip_y, kind="nearest")(ip_q))
    emit_vec("ip_cubic", spn.CubicSpline(ip_x, ip_y)(ip_q))
    emit_vec("ip_cubic_d1", spn.CubicSpline(ip_x, ip_y)(ip_q, 1))
    emit_vec("ip_cubic_nat", spn.CubicSpline(ip_x, ip_y, bc_type="natural")(ip_q))
    emit_vec("ip_pchip", spn.PchipInterpolator(ip_x, ip_y)(ip_q))
    emit_vec("ip_akima", spn.Akima1DInterpolator(ip_x, ip_y)(ip_q))

    # 2-D regular grid
    gx = np.array([0.0, 1.0, 2.0, 3.0])
    gy = np.array([0.0, 1.0, 2.0])
    gv = np.array([[(xi * xi + yi) for yi in gy] for xi in gx])
    rgi_q = np.array([[0.5, 0.5], [1.5, 1.2], [2.7, 0.3], [3.0, 2.0]])
    emit_mat(out, "ip_gv", gv)
    emit_mat(out, "ip_rgi_q", rgi_q)
    emit_vec("ip_rgi_lin", spn.RegularGridInterpolator((gx, gy), gv, method="linear")(rgi_q))
    emit_vec("ip_rgi_near", spn.RegularGridInterpolator((gx, gy), gv, method="nearest")(rgi_q))

    # RBF scattered (2-D)
    rng = np.random.default_rng(0)
    yc = np.array([[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [1.0, 1.0], [0.5, 0.5], [0.2, 0.8], [0.8, 0.3]])
    dvals = np.array([f(p) for p in yc for f in [lambda p: p[0] * p[0] + p[1]]])
    rbf_q = np.array([[0.3, 0.3], [0.6, 0.7], [0.9, 0.1]])
    emit_mat(out, "ip_rbf_y", yc)
    emit_vec("ip_rbf_d", dvals)
    emit_mat(out, "ip_rbf_q", rbf_q)
    emit_vec("ip_rbf_tps", spn.RBFInterpolator(yc, dvals, kernel="thin_plate_spline")(rbf_q))
    emit_vec("ip_rbf_cubic", spn.RBFInterpolator(yc, dvals, kernel="cubic")(rbf_q))
    emit_vec("ip_rbf_lin", spn.RBFInterpolator(yc, dvals, kernel="linear")(rbf_q))

    # B-splines (de Boor evaluation + interpolating builder)
    bx = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
    by = np.array([0.0, 0.8, 0.3, -0.5, 0.2, 1.1, 0.4])
    bxs = np.linspace(-0.4, 6.4, 17)   # includes out-of-range (extrapolation)
    emit_vec("bs_x", bx)
    emit_vec("bs_y", by)
    emit_vec("bs_xs", bxs)
    for k in (1, 2, 3):
        bsp = spn.make_interp_spline(bx, by, k)
        emit_vec(f"bs_t{k}", bsp.t)
        emit_vec(f"bs_c{k}", bsp.c)
        # de Boor on the exact scipy (t, c, k) representation
        emit_vec(f"bs_eval{k}", bsp(bxs))
        # scipy splev on the same tck
        emit_vec(f"bs_splev{k}", spn.splev(bxs, (bsp.t, bsp.c, k)))

    # ---- stats ----
    # distributions: pdf/cdf/ppf at points
    emit_scalar(out, "st_norm_pdf", sst.norm.pdf(0.7, loc=0.2, scale=1.5))
    emit_scalar(out, "st_norm_cdf", sst.norm.cdf(0.7, loc=0.2, scale=1.5))
    emit_scalar(out, "st_norm_ppf", sst.norm.ppf(0.83, loc=0.2, scale=1.5))
    emit_scalar(out, "st_gamma_cdf", sst.gamma.cdf(3.0, 2.5, scale=1.3))
    emit_scalar(out, "st_gamma_ppf", sst.gamma.ppf(0.6, 2.5, scale=1.3))
    emit_scalar(out, "st_chi2_cdf", sst.chi2.cdf(5.0, 3))
    emit_scalar(out, "st_chi2_sf", sst.chi2.sf(5.0, 3))
    emit_scalar(out, "st_beta_cdf", sst.beta.cdf(0.4, 2.0, 3.0))
    emit_scalar(out, "st_beta_ppf", sst.beta.ppf(0.7, 2.0, 3.0))
    emit_scalar(out, "st_t_cdf", sst.t.cdf(1.5, 8))
    emit_scalar(out, "st_t_ppf", sst.t.ppf(0.975, 8))
    emit_scalar(out, "st_f_cdf", sst.f.cdf(2.0, 5, 10))
    emit_scalar(out, "st_f_sf", sst.f.sf(2.0, 5, 10))
    emit_scalar(out, "st_expon_cdf", sst.expon.cdf(2.0, scale=1.5))

    # summary statistics
    sdat = np.array([2.0, 3.5, 1.0, 4.2, 2.8, 3.1, 5.0, 2.2, 3.3, 4.0])
    emit_vec("st_data", sdat)
    emit_scalar(out, "st_gmean", sst.gmean(sdat))
    emit_scalar(out, "st_hmean", sst.hmean(sdat))
    emit_scalar(out, "st_skew", sst.skew(sdat))
    emit_scalar(out, "st_kurtosis", sst.kurtosis(sdat))
    emit_scalar(out, "st_sem", sst.sem(sdat))
    emit_scalar(out, "st_variation", sst.variation(sdat))
    emit_scalar(out, "st_iqr", sst.iqr(sdat))
    tied = np.array([1.0, 2.0, 2.0, 3.0, 3.0, 3.0, 4.0])
    emit_vec("st_tied", tied)
    emit_vec("st_rankdata", sst.rankdata(tied))
    emit_vec("st_zscore", sst.zscore(sdat))

    # correlation / regression
    cx = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0])
    cy = np.array([2.1, 3.9, 6.2, 7.8, 10.1, 12.2, 13.8])
    emit_vec("st_cx", cx); emit_vec("st_cy", cy)
    pr = sst.pearsonr(cx, cy)
    emit_scalar(out, "st_pearson_r", pr[0]); emit_scalar(out, "st_pearson_p", pr[1])
    spr = sst.spearmanr(cx, cy)
    emit_scalar(out, "st_spearman_r", spr.statistic); emit_scalar(out, "st_spearman_p", spr.pvalue)
    lr = sst.linregress(cx, cy)
    emit_scalar(out, "st_lr_slope", lr.slope); emit_scalar(out, "st_lr_intercept", lr.intercept)
    emit_scalar(out, "st_lr_r", lr.rvalue); emit_scalar(out, "st_lr_p", lr.pvalue)
    emit_scalar(out, "st_lr_stderr", lr.stderr)

    # hypothesis tests
    ga = np.array([5.1, 4.9, 6.2, 5.7, 5.5, 6.0, 4.8])
    gb = np.array([6.2, 6.8, 5.9, 7.1, 6.5, 6.9, 7.3])
    emit_vec("st_ga", ga); emit_vec("st_gb", gb)
    t1 = sst.ttest_1samp(ga, 5.0)
    emit_scalar(out, "st_t1_stat", t1.statistic); emit_scalar(out, "st_t1_p", t1.pvalue)
    ti = sst.ttest_ind(ga, gb)
    emit_scalar(out, "st_ti_stat", ti.statistic); emit_scalar(out, "st_ti_p", ti.pvalue)
    tr = sst.ttest_rel(ga, gb)
    emit_scalar(out, "st_tr_stat", tr.statistic); emit_scalar(out, "st_tr_p", tr.pvalue)
    gc = np.array([5.5, 5.8, 6.1, 5.9, 6.0, 5.7, 6.2])
    fo = sst.f_oneway(ga, gb, gc)
    emit_scalar(out, "st_fo_stat", fo.statistic); emit_scalar(out, "st_fo_p", fo.pvalue)
    ks = sst.ks_2samp(ga, gb, method="asymp")
    emit_scalar(out, "st_ks_stat", ks.statistic); emit_scalar(out, "st_ks_p", ks.pvalue)
    ct = np.array([[10.0, 20.0, 30.0], [6.0, 9.0, 17.0]])
    emit_mat(out, "st_ct", ct)
    c2 = sst.chi2_contingency(ct)
    emit_scalar(out, "st_chi2c_stat", c2.statistic); emit_scalar(out, "st_chi2c_p", c2.pvalue)
    emit_mat(out, "st_chi2c_exp", c2.expected_freq)
    nt_data = np.array([2.1, 3.4, 1.9, 5.2, 2.8, 3.3, 4.1, 2.5, 3.9, 2.2, 4.5, 3.0,
                        2.7, 3.6, 1.5, 4.8, 2.9, 3.2, 4.0, 2.6])
    emit_vec("st_nt_data", nt_data)
    ntr = sst.normaltest(nt_data)
    emit_scalar(out, "st_nt_stat", ntr.statistic); emit_scalar(out, "st_nt_p", ntr.pvalue)

    # gaussian_kde (1-D)
    kde_data = np.array([1.0, 1.5, 2.0, 2.2, 3.0, 3.1, 3.5, 4.0, 4.2, 5.0])
    kde_q = np.array([1.5, 2.5, 3.5, 4.5])
    emit_vec("st_kde_data", kde_data); emit_vec("st_kde_q", kde_q)
    emit_vec("st_kde_scott", sst.gaussian_kde(kde_data, bw_method="scott")(kde_q))
    emit_vec("st_kde_silverman", sst.gaussian_kde(kde_data, bw_method="silverman")(kde_q))

    # ---- signal ----
    sa = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    sb = np.array([0.5, 1.0, 0.5])
    emit_vec("sg_a", sa); emit_vec("sg_b", sb)
    emit_vec("sg_conv_full", ssg.convolve(sa, sb, mode="full"))
    emit_vec("sg_conv_same", ssg.convolve(sa, sb, mode="same"))
    emit_vec("sg_conv_valid", ssg.convolve(sa, sb, mode="valid"))
    emit_vec("sg_corr_full", ssg.correlate(sa, sb, mode="full"))

    emit_vec("sg_hann", ssg.windows.hann(16))
    emit_vec("sg_hamming", ssg.windows.hamming(16))
    emit_vec("sg_blackman", ssg.windows.blackman(16))
    emit_vec("sg_kaiser", ssg.windows.kaiser(16, 8.0))
    emit_vec("sg_tukey", ssg.windows.tukey(16, 0.5))
    emit_vec("sg_hann_per", ssg.windows.hann(16, sym=False))

    tw = np.linspace(0, 1, 50, endpoint=False)
    emit_vec("sg_tw", tw)
    emit_vec("sg_chirp", ssg.chirp(tw, f0=2.0, t1=1.0, f1=8.0, method="linear"))
    emit_vec("sg_sawtooth", ssg.sawtooth(2 * np.pi * 3 * tw))
    emit_vec("sg_square", ssg.square(2 * np.pi * 3 * tw, duty=0.3))

    # butter lowpass + filtering
    b, a = ssg.butter(4, 0.2, btype="low")
    emit_vec("sg_butter_b", b); emit_vec("sg_butter_a", a)
    bh, ah = ssg.butter(3, 0.3, btype="high")
    emit_vec("sg_butterhp_b", bh); emit_vec("sg_butterhp_a", ah)
    bbp, abp = ssg.butter(2, [0.2, 0.4], btype="band")
    emit_vec("sg_butterbp_b", bbp); emit_vec("sg_butterbp_a", abp)
    bc1, ac1 = ssg.cheby1(4, 1.0, 0.2, btype="low")
    emit_vec("sg_cheby1_b", bc1); emit_vec("sg_cheby1_a", ac1)
    bc2, ac2 = ssg.cheby2(4, 30.0, 0.2, btype="low")
    emit_vec("sg_cheby2_b", bc2); emit_vec("sg_cheby2_a", ac2)

    sig = np.sin(2 * np.pi * 3 * tw) + 0.4 * np.sin(2 * np.pi * 12 * tw)
    emit_vec("sg_sig", sig)
    emit_vec("sg_lfilter", ssg.lfilter(b, a, sig))
    emit_vec("sg_lfilter_zi", ssg.lfilter_zi(b, a))
    emit_vec("sg_filtfilt", ssg.filtfilt(b, a, sig))
    sos = ssg.butter(4, 0.2, btype="low", output="sos")
    emit_mat(out, "sg_sos", sos)
    emit_vec("sg_sosfilt", ssg.sosfilt(sos, sig))
    emit_vec("sg_detrend", ssg.detrend(sig, type="linear"))

    w, h = ssg.freqz(b, a, worN=32)
    emit_vec("sg_freqz_w", w)
    emit_vec("sg_freqz_hr", h.real); emit_vec("sg_freqz_hi", h.imag)
    hil = ssg.hilbert(sig)
    emit_vec("sg_hilbert_r", hil.real); emit_vec("sg_hilbert_i", hil.imag)

    taps = ssg.firwin(21, 0.3)
    emit_vec("sg_firwin", taps)

    fp, Pp = ssg.periodogram(sig, fs=50.0)
    emit_vec("sg_per_f", fp); emit_vec("sg_per_P", Pp)
    fw, Pw = ssg.welch(sig, fs=50.0, nperseg=16)
    emit_vec("sg_welch_f", fw); emit_vec("sg_welch_P", Pw)

    # ---- signal extras ----
    se_t = np.linspace(0, 1, 64, endpoint=False)
    se_sig = np.sin(2 * np.pi * 4 * se_t) + 0.3 * np.sin(2 * np.pi * 13 * se_t)
    se_sig2 = np.sin(2 * np.pi * 4 * se_t + 0.5) + 0.2 * np.cos(2 * np.pi * 9 * se_t)
    emit_vec("se_sig", se_sig); emit_vec("se_sig2", se_sig2)

    fcs, Pcs = ssg.csd(se_sig, se_sig2, fs=64.0, nperseg=32)
    emit_vec("se_csd_f", fcs); emit_vec("se_csd_re", Pcs.real); emit_vec("se_csd_im", Pcs.imag)
    fco, Cco = ssg.coherence(se_sig, se_sig2, fs=64.0, nperseg=32)
    emit_vec("se_coh", Cco)
    fsp, tsp, Ssp = ssg.spectrogram(se_sig, fs=64.0, nperseg=32)
    emit_vec("se_spec_f", fsp); emit_vec("se_spec_t", tsp); emit_mat(out, "se_spec_S", Ssp)
    fst, tst, Zst = ssg.stft(se_sig, fs=64.0, nperseg=32)
    emit_mat(out, "se_stft_re", Zst.real); emit_mat(out, "se_stft_im", Zst.imag)
    _, xrec = ssg.istft(Zst, fs=64.0, nperseg=32)
    emit_vec("se_istft", xrec[:64])

    # peaks
    pk_x = np.array([0., 1., 0., 2., 1., 3., 0., 1., 4., 1., 0., 2., 0.])
    emit_vec("se_pk_x", pk_x)
    pk, _ = ssg.find_peaks(pk_x)
    emit_vec("se_peaks", pk.astype(float))
    pk2, _ = ssg.find_peaks(pk_x, height=2.0)
    emit_vec("se_peaks_h", pk2.astype(float))
    prom = ssg.peak_prominences(pk_x, pk)[0]
    emit_vec("se_prom", prom)
    wid = ssg.peak_widths(pk_x, pk)[0]
    emit_vec("se_width", wid)

    # LTI: H(s) = 1/(s^2 + 0.5 s + 1)
    num = [1.0]; den = [1.0, 0.5, 1.0]
    lw = np.logspace(-1, 1, 32)
    _, lh = ssg.freqresp((num, den), w=lw)
    emit_vec("se_fr_re", lh.real); emit_vec("se_fr_im", lh.imag)
    _, lmag, lph = ssg.bode((num, den), w=lw)
    emit_vec("se_bode_mag", lmag); emit_vec("se_bode_ph", lph)
    lt = np.linspace(0, 20, 60)
    _, lstep = ssg.step((num, den), T=lt)
    emit_vec("se_step", lstep)
    _, limp = ssg.impulse((num, den), T=lt)
    emit_vec("se_impulse", limp)
    lu = np.sin(lt)
    _, ly, _ = ssg.lsim((num, den), U=lu, T=lt)
    emit_vec("se_lsim", ly)

    # ---- discrete-time LTI ----
    dA, dB, dC, dD = ssg.tf2ss(num, den)
    ddt = 0.1
    dAd, dBd, dCd, dDd, _ = ssg.cont2discrete((dA, dB, dC, dD), ddt, method="zoh")
    emit_mat(out, "se_d_Ad", dAd); emit_vec("se_d_Bd", dBd.ravel())
    emit_vec("se_d_Cd", dCd.ravel()); emit_vec("se_d_Dd", dDd.ravel())
    bAd, bBd, bCd, bDd, _ = ssg.cont2discrete((dA, dB, dC, dD), ddt, method="bilinear")
    emit_mat(out, "se_db_Ad", bAd); emit_vec("se_db_Bd", bBd.ravel())
    emit_vec("se_db_Cd", bCd.ravel()); emit_vec("se_db_Dd", bDd.ravel())
    eAd, eBd, eCd, eDd, _ = ssg.cont2discrete((dA, dB, dC, dD), ddt, method="euler")
    emit_mat(out, "se_de_Ad", eAd); emit_vec("se_de_Bd", eBd.ravel())
    nstep = 30
    _, dys = ssg.dstep((dAd, dBd, dCd, dDd, ddt), n=nstep)
    emit_vec("se_dstep", np.asarray(dys[0]).ravel())
    _, dyi = ssg.dimpulse((dAd, dBd, dCd, dDd, ddt), n=nstep)
    emit_vec("se_dimpulse", np.asarray(dyi[0]).ravel())
    du = np.sin(np.arange(nstep) * ddt)
    emit_vec("se_du", du)
    _, dyl, _ = ssg.dlsim((dAd, dBd, dCd, dDd, ddt), du)
    emit_vec("se_dlsim", np.asarray(dyl).ravel())
    dw = np.logspace(-2, np.log10(np.pi), 32)
    _, dh = ssg.dfreqresp((dAd, dBd, dCd, dDd, ddt), w=dw)
    emit_vec("se_dw", dw); emit_vec("se_dfr_re", dh.real); emit_vec("se_dfr_im", dh.imag)
    _, dmag, dph = ssg.dbode((dAd, dBd, dCd, dDd, ddt), w=dw)
    emit_vec("se_dbode_mag", dmag); emit_vec("se_dbode_ph", dph)

    # resampling
    emit_vec("se_resample", ssg.resample(se_sig, 96))
    emit_vec("se_resample_poly", ssg.resample_poly(se_sig, 3, 2))
    emit_vec("se_decimate", ssg.decimate(se_sig, 2))
    uh = np.array([0.25, 0.5, 0.25]); ux = np.array([1.0, 2.0, 3.0, 4.0])
    emit_vec("se_uh", uh); emit_vec("se_ux", ux)
    emit_vec("se_upfirdn", ssg.upfirdn(uh, ux, 2, 1))

    # ellip / bessel: validate by freqz magnitude response
    be, ae = ssg.ellip(4, 1, 40, 0.3, btype="low")
    we, he = ssg.freqz(be, ae, worN=48)
    emit_vec("se_ellip_mag", np.abs(he))
    bb, ab = ssg.bessel(4, 0.3, btype="low")
    wb, hb = ssg.freqz(bb, ab, worN=48)
    emit_vec("se_bessel_mag", np.abs(hb))

    # savgol / medfilt / wiener / 2-D
    emit_vec("se_savgol_coeffs", ssg.savgol_coeffs(7, 2))
    emit_vec("se_savgol", ssg.savgol_filter(se_sig, 7, 2))
    emit_vec("se_medfilt", ssg.medfilt(se_sig, 5))
    emit_vec("se_wiener", ssg.wiener(se_sig, 5))
    A2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
    B2 = np.array([[1., 0.], [0., -1.]])
    emit_mat(out, "se_A2", A2); emit_mat(out, "se_B2", B2)
    emit_mat(out, "se_conv2d", ssg.convolve2d(A2, B2, mode="full"))
    emit_mat(out, "se_conv2d_same", ssg.convolve2d(A2, B2, mode="same"))
    emit_mat(out, "se_corr2d", ssg.correlate2d(A2, B2, mode="full"))

    # ---- sparse ----
    Asp = np.array([[4., 0., 1., 0.], [0., 3., 0., 2.], [1., 0., 5., 0.], [0., 2., 0., 6.]])
    emit_mat(out, "sp_A", Asp)
    csr = ssp.csr_array(Asp)
    emit_mat(out, "sp_A_toarray", csr.toarray())
    xv = np.array([1., 2., 3., 4.])
    emit_vec("sp_x", xv)
    emit_vec("sp_spmv", csr @ xv)
    Xm = np.array([[1., 0.], [0., 1.], [2., 1.], [1., 2.]])
    emit_mat(out, "sp_X", Xm)
    emit_mat(out, "sp_spmm", (csr @ Xm))
    emit_vec("sp_diag", csr.diagonal())
    emit_scalar(out, "sp_norm_fro", sspl.norm(csr))
    emit_mat(out, "sp_eye", ssp.eye_array(4).toarray())
    dd = ssp.diags([np.array([1., 2., 3., 4.]), np.array([5., 6., 7.])], [0, 1]).toarray()
    emit_mat(out, "sp_diags", dd)
    Bsum = (csr + ssp.eye_array(4)).toarray()
    emit_mat(out, "sp_add", Bsum)

    # solvers (SPD system)
    bb = np.array([1., 2., 3., 4.])
    emit_vec("sp_b", bb)
    emit_vec("sp_spsolve", sspl.spsolve(ssp.csr_array(Asp), bb))

    # ---- stiff SPD system for preconditioned iterative + sparse-direct solvers ----
    # A 1-D Dirichlet Laplacian tri(-1, 2, -1) (SPD) put through a positive diagonal
    # congruence D K D with widely varying D — SPD but ill-conditioned, so
    # unpreconditioned CG stalls while Jacobi/IC0 preconditioning converges fast.
    def emit_ivec(name, arr):
        arr = np.asarray(arr).ravel().astype(np.int64)
        out.append(f"inline const long long {name}[] = {{{', '.join(str(int(v)) for v in arr)}}};")
        out.append(f"inline constexpr int {name}_n = {len(arr)};")

    def emit_csr(name, M):
        M = ssp.csr_array(M)
        M.sort_indices()
        emit_vec(f"{name}_data", M.data.astype(float))
        emit_ivec(f"{name}_indices", M.indices)
        emit_ivec(f"{name}_indptr", M.indptr)
        emit_scalar(out, f"{name}_rows", float(M.shape[0]))
        emit_scalar(out, f"{name}_cols", float(M.shape[1]))

    nstiff = 80
    lap = ssp.diags([-1.0, 2.0, -1.0], [-1, 0, 1], shape=(nstiff, nstiff))
    scale = np.logspace(0.0, 2.0, nstiff)                 # 1 .. 100 diagonal weights
    Dsc = ssp.diags(scale)
    Kspd = (Dsc @ lap @ Dsc).tocsr()
    Kspd.sort_indices()
    emit_csr("sp_spd", Kspd)
    b_spd = np.ones(nstiff)
    emit_vec("sp_spd_b", b_spd)
    emit_vec("sp_spd_x", sspl.spsolve(ssp.csr_array(Kspd), b_spd))

    # General non-symmetric sparse system for sparse LU (direct) parity.
    rng_lu = np.random.default_rng(7)
    ngen = 40
    Agen = ssp.random(ngen, ngen, density=0.08, random_state=rng_lu, format="csr")
    Agen = Agen + ssp.diags(np.full(ngen, 5.0))          # strong diagonal → nonsingular
    Agen = Agen.tocsr(); Agen.sort_indices()
    emit_csr("sp_gen", Agen)
    b_gen = np.arange(1.0, ngen + 1.0)
    emit_vec("sp_gen_b", b_gen)
    emit_vec("sp_gen_x", sspl.spsolve(ssp.csr_array(Agen), b_gen))

    # SPD "arrow" matrix: dense first row/column + diagonal. Eliminating the hub
    # node first (natural order) fills the whole trailing block; RCM orders the
    # hub last and induces almost no fill — a clean RCM-reduces-fill case.
    narr = 30
    Karr = np.zeros((narr, narr))
    for i in range(narr):
        Karr[i, i] = 2.0
    Karr[0, 0] = float(narr + 2)
    for i in range(1, narr):
        Karr[0, i] = Karr[i, 0] = 1.0            # SPD (diagonally dominant)
    emit_csr("sp_arrow", Karr)
    b_arr = np.ones(narr)
    emit_vec("sp_arrow_b", b_arr)
    emit_vec("sp_arrow_x", sspl.spsolve(ssp.csr_array(Karr), b_arr))

    # Symmetric indefinite (negative-definite) system: Cholesky must reject it
    # and the solver fall back to LU, still matching SciPy.
    nind = 20
    Kind = -(ssp.diags([-1.0, 2.0, -1.0], [-1, 0, 1], shape=(nind, nind))).toarray()
    emit_csr("sp_indef", Kind)
    b_ind = np.arange(1.0, nind + 1.0)
    emit_vec("sp_indef_b", b_ind)
    emit_vec("sp_indef_x", sspl.spsolve(ssp.csr_array(Kind), b_ind))

    # ---- generalized symmetric eigenproblem K x = λ M x (shift-invert eigsh) ----
    # A 1-D bar: stiffness K = tri(-1, 2, -1) (SPD with fixed ends) and consistent
    # mass M = tri(1, 4, 1)/6 (SPD). Both are large-enough to force the sparse
    # path; the lowest-k modes are computed by shift-invert Lanczos at sigma=0.
    neig = 64
    Keig = ssp.diags([-1.0, 2.0, -1.0], [-1, 0, 1], shape=(neig, neig)).tocsr()
    Meig = (ssp.diags([1.0, 4.0, 1.0], [-1, 0, 1], shape=(neig, neig)) / 6.0).tocsr()
    Keig.sort_indices(); Meig.sort_indices()
    emit_csr("sp_eig_K", Keig)
    emit_csr("sp_eig_M", Meig)
    keig = 6
    emit_scalar(out, "sp_eig_k", float(keig))
    w_eig = sspl.eigsh(Keig, k=keig, M=Meig, sigma=0.0, which="LM",
                       return_eigenvectors=False)
    emit_vec("sp_eig_vals", np.sort(w_eig))

    # csgraph (weighted directed graph)
    G = np.array([[0., 2., 0., 6.], [0., 0., 3., 8.], [0., 0., 0., 0.], [0., 0., 7., 0.]])
    emit_mat(out, "sp_G", G)
    gcsr = ssp.csr_array(G)
    emit_mat(out, "sp_dijkstra", sscg.dijkstra(gcsr, directed=True))
    emit_mat(out, "sp_floyd", sscg.floyd_warshall(gcsr, directed=True))
    # connected components (undirected)
    Gu = np.array([[0., 1., 0., 0., 0.], [1., 0., 0., 0., 0.], [0., 0., 0., 1., 0.],
                   [0., 0., 1., 0., 0.], [0., 0., 0., 0., 0.]])
    emit_mat(out, "sp_Gu", Gu)
    ncomp, lbl = sscg.connected_components(ssp.csr_array(Gu), directed=False)
    emit_scalar(out, "sp_ncomp", float(ncomp))
    # MST total weight
    Gm = np.array([[0., 1., 0., 4.], [1., 0., 2., 6.], [0., 2., 0., 3.], [4., 6., 3., 0.]])
    emit_mat(out, "sp_Gm", Gm)
    mst = sscg.minimum_spanning_tree(ssp.csr_array(Gm))
    emit_scalar(out, "sp_mst_weight", mst.toarray().sum())

    # traversal: breadth/depth-first order + predecessors
    Gt = np.array([[0., 1., 0., 0., 1.], [0., 0., 1., 0., 0.], [0., 0., 0., 1., 0.],
                   [0., 0., 0., 0., 0.], [0., 0., 1., 1., 0.]])
    emit_mat(out, "sp_Gt", Gt)
    gt = ssp.csr_array(Gt)
    bno, bpr = sscg.breadth_first_order(gt, 0, directed=True)
    emit_vec("sp_bfs_node", bno.astype(float))
    emit_vec("sp_bfs_pred", bpr.astype(float))
    dno, dpr = sscg.depth_first_order(gt, 0, directed=True)
    emit_vec("sp_dfs_node", dno.astype(float))
    emit_vec("sp_dfs_pred", dpr.astype(float))
    # undirected traversal on a branchier graph (out-then-in neighbour order)
    Gtu = np.array([[0., 0., 1., 0., 0., 1.], [1., 0., 0., 0., 0., 0.],
                    [0., 0., 0., 1., 0., 0.], [0., 0., 0., 0., 0., 0.],
                    [0., 1., 0., 0., 0., 0.], [0., 0., 0., 0., 1., 0.]])
    emit_mat(out, "sp_Gtu", Gtu)
    gtu = ssp.csr_array(Gtu)
    uno, upr = sscg.breadth_first_order(gtu, 0, directed=False)
    emit_vec("sp_bfsu_node", uno.astype(float))
    emit_vec("sp_bfsu_pred", upr.astype(float))
    vno, vpr = sscg.depth_first_order(gtu, 0, directed=False)
    emit_vec("sp_dfsu_node", vno.astype(float))
    emit_vec("sp_dfsu_pred", vpr.astype(float))

    # johnson all-pairs (negative edges, directed)
    Gj = np.array([[0., -2., 0., 0.], [0., 0., 2., 0.], [0., 0., 0., -1.], [3., 0., 0., 0.]])
    emit_mat(out, "sp_Gj", Gj)
    emit_mat(out, "sp_johnson", sscg.johnson(ssp.csr_array(Gj), directed=True))

    # maximum flow (integer capacities)
    Gf = np.array([[0., 3., 0., 3., 0., 0., 0.], [0., 0., 4., 0., 0., 0., 0.],
                   [3., 0., 0., 1., 2., 0., 0.], [0., 0., 0., 0., 0., 6., 0.],
                   [0., 0., 0., 0., 0., 0., 1.], [0., 0., 6., 0., 0., 0., 9.],
                   [0., 0., 0., 0., 0., 0., 0.]])
    emit_mat(out, "sp_Gf", Gf)
    fres = sscg.maximum_flow(ssp.csr_array(Gf.astype(np.int64)), 0, 6)
    emit_scalar(out, "sp_flow_value", float(fres.flow_value))

    # maximum bipartite matching (graphs with unique maximum matchings)
    Gb = np.array([[1., 0., 0.], [1., 1., 0.], [0., 0., 1.]])
    emit_mat(out, "sp_Gb", Gb)
    emit_vec("sp_bm_row", sscg.maximum_bipartite_matching(ssp.csr_array(Gb), "row").astype(float))
    emit_vec("sp_bm_col", sscg.maximum_bipartite_matching(ssp.csr_array(Gb), "column").astype(float))
    Gb2 = np.array([[1., 0.], [0., 1.], [0., 0.]])
    emit_mat(out, "sp_Gb2", Gb2)
    emit_vec("sp_bm2_col", sscg.maximum_bipartite_matching(ssp.csr_array(Gb2), "column").astype(float))

    # ---- spatial ----
    P = np.array([[0., 0.], [1., 0.], [0., 1.], [1., 1.], [0.5, 0.3], [0.2, 0.8]])
    Q = np.array([[2., 2.], [0.5, 0.5], [3., 1.]])
    emit_mat(out, "sa_P", P); emit_mat(out, "sa_Q", Q)
    for m in ["euclidean", "cityblock", "chebyshev", "cosine", "correlation", "hamming"]:
        emit_vec(f"sa_pdist_{m}", spd.pdist(P, metric=m))
    emit_mat(out, "sa_cdist_eucl", spd.cdist(P, Q, metric="euclidean"))
    emit_mat(out, "sa_squareform", spd.squareform(spd.pdist(P)))

    # KDTree
    tree = KDTree(P)
    dd, ii = tree.query(Q, k=2)
    emit_mat(out, "sa_kd_dist", dd)
    emit_mat(out, "sa_kd_idx", ii.astype(float))

    # ConvexHull (2-D)
    hull = ConvexHull(P)
    emit_scalar(out, "sa_hull_area", hull.area)      # perimeter (2-D)
    emit_scalar(out, "sa_hull_volume", hull.volume)  # area (2-D)
    emit_vec("sa_hull_vertices", np.sort(hull.vertices).astype(float))

    # Delaunay (2-D): general-position points (unique triangulation), sorted tris
    DP = np.array([[0.0, 0.0], [1.0, 0.2], [0.3, 1.0], [1.2, 1.1], [0.6, 0.4], [0.1, 0.7]])
    emit_mat(out, "sa_DP", DP)
    dela = Delaunay(DP)
    tris = np.sort(dela.simplices, axis=1)
    tris = tris[np.lexsort(tris.T[::-1])]
    emit_mat(out, "sa_delaunay", tris.astype(float))
    emit_scalar(out, "sa_find_simplex_in", float(dela.find_simplex([0.5, 0.5]) >= 0))

    # Rotation
    r = spR.from_euler("xyz", [30, 45, 60], degrees=True)
    emit_mat(out, "sa_rot_matrix", r.as_matrix())
    emit_vec("sa_rot_quat", r.as_quat())
    emit_vec("sa_rot_apply", r.apply([1., 2., 3.]))
    emit_vec("sa_rot_euler", r.as_euler("xyz", degrees=True))
    emit_vec("sa_rot_rotvec", r.as_rotvec())
    emit_scalar(out, "sa_rot_mag", r.magnitude())
    r2 = spR.from_quat([0.1, 0.2, 0.3, 0.9])
    comp = (r * r2)
    emit_vec("sa_rot_compose_apply", comp.apply([1., 0., 0.]))
    emit_vec("sa_rot_inv_apply", r.inv().apply([1., 2., 3.]))
    # Slerp
    key_t = np.array([0., 1., 2.])
    key_r = spR.from_euler("z", [0, 90, 180], degrees=True)
    sl = spSlerp(key_t, key_r)
    emit_vec("sa_slerp_apply", sl(0.7).apply([1., 0., 0.]))

    # ---- ndimage ----
    rng = np.random.default_rng(1)
    I = np.array([[1., 2., 3., 4., 5.], [2., 4., 6., 8., 10.], [1., 3., 5., 7., 9.],
                  [0., 2., 4., 6., 8.], [5., 4., 3., 2., 1.]])
    emit_mat(out, "ni_I", I)
    for m in ["reflect", "nearest", "mirror", "wrap", "constant"]:
        emit_mat(out, f"ni_gauss_{m}", sni.gaussian_filter(I, 1.0, mode=m))
    emit_mat(out, "ni_uniform", sni.uniform_filter(I, 3))
    emit_mat(out, "ni_median", sni.median_filter(I, 3))
    emit_mat(out, "ni_minimum", sni.minimum_filter(I, 3))
    emit_mat(out, "ni_maximum", sni.maximum_filter(I, 3))
    emit_mat(out, "ni_sobel0", sni.sobel(I, axis=0))
    emit_mat(out, "ni_sobel1", sni.sobel(I, axis=1))
    emit_mat(out, "ni_laplace", sni.laplace(I))
    emit_vec("ni_corr1d", sni.correlate1d(I[0], np.array([1., 2., 1.])))
    # correlate1d across boundary modes (asymmetric weights + origin shift) to
    # regression-test the NumPP-delegated separable correlation path.
    c1d_sig = np.array([1., 2., 3., 4., 5., 4., 3.])
    c1d_w = np.array([0.25, 0.5, -0.25])
    for m in ["reflect", "nearest", "mirror", "wrap", "constant"]:
        emit_vec(f"ni_c1d_{m}", sni.correlate1d(c1d_sig, c1d_w, mode=m, cval=2.0))
    emit_vec("ni_c1d_origin", sni.correlate1d(c1d_sig, c1d_w, mode="reflect", origin=1))
    emit_vec("ni_c1d_sig", c1d_sig)
    emit_vec("ni_c1d_wts", c1d_w)

    # morphology
    B = np.array([[0., 0., 0., 0., 0.], [0., 1., 1., 1., 0.], [0., 1., 1., 1., 0.],
                  [0., 1., 1., 1., 0.], [0., 0., 0., 0., 0.]])
    emit_mat(out, "ni_B", B)
    emit_mat(out, "ni_erosion", sni.binary_erosion(B).astype(float))
    emit_mat(out, "ni_dilation", sni.binary_dilation(B).astype(float))
    emit_mat(out, "ni_opening", sni.binary_opening(B).astype(float))
    emit_mat(out, "ni_grey_erosion", sni.grey_erosion(I, size=3))
    emit_mat(out, "ni_edt", sni.distance_transform_edt(B))

    # measurements
    Limg = np.array([[1., 1., 0., 0., 1.], [1., 0., 0., 1., 1.], [0., 0., 0., 0., 0.],
                     [1., 1., 0., 1., 0.], [1., 0., 0., 1., 0.]])
    emit_mat(out, "ni_Limg", Limg)
    lab, num = sni.label(Limg)
    emit_scalar(out, "ni_label_num", float(num))
    emit_mat(out, "ni_label", lab.astype(float))
    emit_vec("ni_com", np.array(sni.center_of_mass(I)))
    emit_scalar(out, "ni_sum", float(sni.sum(I)))

    # geometric transforms (order 0 and 1)
    emit_mat(out, "ni_shift1", sni.shift(I, [1.0, 0.5], order=1))
    emit_mat(out, "ni_affine1", sni.affine_transform(I, np.array([[1., 0.2], [-0.1, 1.]]),
                                                     offset=[0.3, -0.2], order=1))
    emit_mat(out, "ni_zoom1", sni.zoom(I, 1.5, order=1))
    emit_mat(out, "ni_rotate1", sni.rotate(I, 30.0, order=1, reshape=False))
    coords = np.array([[0.5, 1.5, 2.2, 3.0], [1.0, 2.5, 0.8, 4.0]])
    emit_mat(out, "ni_coords", coords)
    emit_vec("ni_mapcoord", sni.map_coordinates(I, coords, order=1))

    # ---- cluster ----
    obs = np.array([[1.9, 2.3], [1.5, 2.5], [0.8, 0.6], [0.4, 1.8], [3.0, 3.2],
                    [2.7, 2.9], [0.5, 0.5], [3.1, 3.0]])
    emit_mat(out, "cl_obs", obs)
    emit_mat(out, "cl_whiten", scv.whiten(obs))
    cb = np.array([[1.0, 1.0], [3.0, 3.0]])
    emit_mat(out, "cl_cb", cb)
    code, dist = scv.vq(obs, cb)
    emit_vec("cl_vq_code", code.astype(float)); emit_vec("cl_vq_dist", dist)
    cent, lab = scv.kmeans2(obs, cb, iter=10, minit="matrix")
    emit_mat(out, "cl_km_centroids", cent)
    emit_vec("cl_km_labels", lab.astype(float))

    pts = np.array([[0.0, 0.0], [0.2, 0.1], [3.0, 3.0], [3.2, 2.9], [6.0, 0.5], [6.1, 0.7]])
    emit_mat(out, "cl_pts", pts)
    for meth in ["single", "complete", "average", "ward"]:
        emit_mat(out, f"cl_link_{meth}", sch.linkage(pts, method=meth))
    Zc = sch.linkage(pts, method="average")
    emit_vec("cl_cophenet", sch.cophenet(Zc))
    emit_vec("cl_fcluster", sch.fcluster(Zc, 3, criterion="maxclust").astype(float))

    # ---- io: write golden sample files, emit expected values ----
    gdir = os.path.join(ROOT, "tests", "golden")
    from scipy.sparse import csr_array
    mm_A = np.array([[5., 0., 0., 1.], [0., 8., 0., 0.], [0., 0., 3., 2.]])
    mmwrite(os.path.join(gdir, "sample.mtx"), csr_array(mm_A))
    emit_mat(out, "io_mm", mm_A)

    wav_rate = 8000
    wav_data = np.array([0, 1000, -2000, 32000, -32000, 500, -500, 0], dtype=np.int16)
    wavfile.write(os.path.join(gdir, "sample.wav"), wav_rate, wav_data)
    emit_scalar(out, "io_wav_rate", float(wav_rate))
    emit_vec("io_wav", wav_data.astype(float))

    with open(os.path.join(gdir, "sample.arff"), "w") as af:
        af.write("@relation test\n@attribute a numeric\n@attribute b numeric\n@attribute c numeric\n@data\n")
        af.write("1.0,2.0,3.0\n4.5,5.5,6.5\n7.0,8.0,9.0\n")
    emit_mat(out, "io_arff", np.array([[1.0, 2.0, 3.0], [4.5, 5.5, 6.5], [7.0, 8.0, 9.0]]))

    # ---- discrete distributions + rank tests ----
    emit_vec("dd_binom_pmf", [sst.binom.pmf(k, 10, 0.35) for k in range(11)])
    emit_vec("dd_binom_cdf", [sst.binom.cdf(k, 10, 0.35) for k in range(11)])
    emit_scalar(out, "dd_binom_ppf", float(sst.binom.ppf(0.7, 10, 0.35)))
    emit_vec("dd_poisson_pmf", [sst.poisson.pmf(k, 3.2) for k in range(10)])
    emit_vec("dd_poisson_cdf", [sst.poisson.cdf(k, 3.2) for k in range(10)])
    emit_vec("dd_geom_pmf", [sst.geom.pmf(k, 0.3) for k in range(1, 8)])
    emit_vec("dd_geom_cdf", [sst.geom.cdf(k, 0.3) for k in range(1, 8)])
    emit_vec("dd_nbinom_pmf", [sst.nbinom.pmf(k, 5, 0.4) for k in range(10)])
    emit_vec("dd_nbinom_cdf", [sst.nbinom.cdf(k, 5, 0.4) for k in range(10)])
    emit_vec("dd_hypergeom_pmf", [sst.hypergeom.pmf(k, 20, 7, 12) for k in range(8)])
    emit_vec("dd_hypergeom_cdf", [sst.hypergeom.cdf(k, 20, 7, 12) for k in range(8)])
    emit_scalar(out, "dd_binom_mean", float(sst.binom.mean(10, 0.35)))
    emit_scalar(out, "dd_nbinom_var", float(sst.nbinom.var(5, 0.4)))

    rx = np.array([1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 2.0])
    ry = np.array([2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 1.5, 14.0])
    emit_vec("dd_rx", rx); emit_vec("dd_ry", ry)
    mw = sst.mannwhitneyu(rx, ry, method="asymptotic")
    emit_scalar(out, "dd_mw_stat", mw.statistic); emit_scalar(out, "dd_mw_p", mw.pvalue)
    wl = sst.wilcoxon(rx, ry, method="approx")
    emit_scalar(out, "dd_wl_stat", wl.statistic); emit_scalar(out, "dd_wl_p", wl.pvalue)
    g1 = np.array([2.1, 3.4, 1.9, 5.2]); g2 = np.array([4.1, 5.5, 6.0, 3.8]); g3 = np.array([1.2, 2.2, 0.9, 1.8])
    emit_vec("dd_g1", g1); emit_vec("dd_g2", g2); emit_vec("dd_g3", g3)
    kr = sst.kruskal(g1, g2, g3)
    emit_scalar(out, "dd_kr_stat", kr.statistic); emit_scalar(out, "dd_kr_p", kr.pvalue)
    kt = sst.kendalltau(rx, ry, method="asymptotic")
    emit_scalar(out, "dd_kt_stat", kt.statistic); emit_scalar(out, "dd_kt_p", kt.pvalue)

    # ---- normality tests: shapiro + anderson ----
    nrm = np.array([2.1, 3.4, 1.9, 5.2, 2.8, 3.3, 4.1, 2.5, 3.9, 2.2, 4.5, 3.0,
                    2.7, 3.6, 1.5, 4.8, 2.9, 3.2, 4.0, 2.6])
    skw = np.array([1.0, 1.2, 1.1, 1.5, 2.0, 1.3, 1.8, 5.0, 1.1, 1.4, 2.2, 1.6,
                    1.0, 3.5, 1.2, 1.7, 4.1, 1.3, 1.9, 1.1])
    sml = np.array([1.0, 2.0, 4.0])
    emit_vec("nm_normal", nrm); emit_vec("nm_skew", skw); emit_vec("nm_small", sml)
    for tag, d in (("normal", nrm), ("skew", skw), ("small", sml)):
        sw = sst.shapiro(d)
        emit_scalar(out, f"nm_{tag}_sw_W", float(sw.statistic))
        emit_scalar(out, f"nm_{tag}_sw_p", float(sw.pvalue))
    for tag, d in (("normal", nrm), ("skew", skw)):
        ad = sst.anderson(d, "norm")
        emit_scalar(out, f"nm_{tag}_ad_A2", float(ad.statistic))
        emit_vec(f"nm_{tag}_ad_crit", ad.critical_values)
        emit_vec(f"nm_{tag}_ad_sig", ad.significance_level)

    # ---- linprog + nnls ----
    # LP1: min -x0 -2x1  s.t. x0+x1<=4, x0+3x1<=6  -> vertex (3,1), fun -5
    lp1 = spo.linprog([-1, -2], A_ub=[[1, 1], [1, 3]], b_ub=[4, 6], bounds=(0, None))
    emit_vec("lp1_x", lp1.x); emit_scalar(out, "lp1_fun", float(lp1.fun))
    # LP2: equality + inequality. min x0+x1 s.t. x0+2x1>=3 (-> -x0-2x1<=-3), x0+x1=2
    lp2 = spo.linprog([1, 1], A_ub=[[-1, -2]], b_ub=[-3], A_eq=[[1, 1]], b_eq=[2], bounds=(0, None))
    emit_vec("lp2_x", lp2.x); emit_scalar(out, "lp2_fun", float(lp2.fun))
    # LP3: classic min c=[-3,-2,-4] with 3 ub constraints
    lp3 = spo.linprog([-3, -2, -4], A_ub=[[1, 1, 1], [2, 1, 0], [0, 1, 2]],
                      b_ub=[10, 8, 12], bounds=(0, None))
    emit_vec("lp3_x", lp3.x); emit_scalar(out, "lp3_fun", float(lp3.fun))

    nnls_A = np.array([[1.0, 0.0], [1.0, 1.0], [0.0, 1.0], [2.0, 1.0]])
    nnls_b = np.array([1.0, 2.0, 1.5, 3.0])
    nx, nr = spo.nnls(nnls_A, nnls_b)
    emit_mat(out, "nnls_A", nnls_A); emit_vec("nnls_b", nnls_b)
    emit_vec("nnls_x", nx); emit_scalar(out, "nnls_rnorm", float(nr))
    # nnls case where the unconstrained solution has a negative component
    nnls_A2 = np.array([[1.0, 1.0], [1.0, -1.0], [1.0, 2.0]])
    nnls_b2 = np.array([2.0, 5.0, 1.0])
    nx2, nr2 = spo.nnls(nnls_A2, nnls_b2)
    emit_mat(out, "nnls_A2", nnls_A2); emit_vec("nnls_b2", nnls_b2)
    emit_vec("nnls_x2", nx2); emit_scalar(out, "nnls_rnorm2", float(nr2))

    # ---- griddata (scattered 2-D interpolation) ----
    gpts = np.array([[0.0, 0.0], [2.0, 0.0], [2.0, 2.0], [0.0, 2.0],
                     [1.0, 1.0], [0.5, 1.5], [1.6, 0.4], [1.3, 1.7]])
    # Linear field: linear interpolation is exact and triangulation-independent.
    gval_lin = 2.0 * gpts[:, 0] + 3.0 * gpts[:, 1] + 1.0
    # Nonlinear field for the nearest-neighbour case.
    gval_nl = gpts[:, 0] ** 2 + gpts[:, 1]
    gxi = np.array([[0.8, 0.8], [1.2, 1.0], [1.0, 1.2], [0.6, 0.6], [5.0, 5.0]])
    emit_mat(out, "gd_pts", gpts)
    emit_vec("gd_val_lin", gval_lin)
    emit_vec("gd_val_nl", gval_nl)
    emit_mat(out, "gd_xi", gxi)
    emit_vec("gd_linear", spn.griddata(gpts, gval_lin, gxi, method="linear"))
    emit_vec("gd_nearest", spn.griddata(gpts, gval_nl, gxi, method="nearest"))

    # ---- stiff ODE: solve_ivp method="Radau" ----
    # Problem 1: y' = -20 y, y0 = 1  (exact exp(-20 t)).
    te1 = np.array([0.0, 0.1, 0.25, 0.5, 1.0])
    s1 = spi.solve_ivp(lambda t, y: -20.0 * y, (0.0, 1.0), [1.0],
                       method="Radau", t_eval=te1, rtol=1e-8, atol=1e-11)
    emit_vec("ode_radau1_t", te1)
    emit_vec("ode_radau1_y", s1.y[0])
    # Problem 2: stiff 2-D y1' = -100 y1 + y2, y2' = -y2, y0 = [1, 1].
    te2 = np.array([0.0, 0.05, 0.2, 0.5, 1.0])
    s2 = spi.solve_ivp(lambda t, y: [-100 * y[0] + y[1], -y[1]], (0.0, 1.0), [1.0, 1.0],
                       method="Radau", t_eval=te2, rtol=1e-9, atol=1e-12)
    emit_vec("ode_radau2_t", te2)
    emit_mat(out, "ode_radau2_y", s2.y)  # shape (2, 5)

    # ---- stiff ODE: solve_ivp method="BDF" (validated against analytic solution) ----
    # Problem 1: y' = -20 y, y0 = 1  (exact exp(-20 t)).
    tb1 = np.array([0.0, 0.1, 0.25, 0.5, 1.0])
    emit_vec("ode_bdf1_t", tb1)
    emit_vec("ode_bdf1_y", np.exp(-20.0 * tb1))
    # Problem 2: stiff 2-D y1' = -100 y1 + y2, y2' = -y2, y0 = [1, 1].
    # Analytic: y2 = exp(-t); y1 = (1 - 1/99) exp(-100 t) + (1/99) exp(-t).
    tb2 = np.array([0.0, 0.05, 0.2, 0.5, 1.0])
    y1b = (1.0 - 1.0 / 99.0) * np.exp(-100.0 * tb2) + (1.0 / 99.0) * np.exp(-tb2)
    y2b = np.exp(-tb2)
    emit_vec("ode_bdf2_t", tb2)
    emit_mat(out, "ode_bdf2_y", np.vstack([y1b, y2b]))  # shape (2, 5)

    # ---- nested / extended quadrature ----
    # romberg was removed from scipy in 1.15; reference its value via quad (same oracle).
    emit_scalar(out, "romberg_sin", spi.quad(np.sin, 0.0, np.pi)[0])            # = 2
    emit_scalar(out, "romberg_gauss", spi.quad(lambda x: np.exp(-x * x), 0.0, 1.0)[0])
    # quad_vec of f(x) = [1, x, x^2, sin x] over [0, 1]
    qv = spi.quad_vec(lambda x: np.array([1.0, x, x * x, np.sin(x)]), 0.0, 1.0)[0]
    emit_vec("quadvec", qv)
    # dblquad: ∫_0^1 ∫_0^{2} x*y dy dx = 1 ; func(y, x)=x*y
    d1 = spi.dblquad(lambda y, x: x * y, 0, 1, lambda x: 0, lambda x: 2)[0]
    emit_scalar(out, "dblquad_xy", d1)
    # dblquad with x-dependent bounds: ∫_0^1 ∫_0^{x} (x+y) dy dx
    d2 = spi.dblquad(lambda y, x: x + y, 0, 1, lambda x: 0, lambda x: x)[0]
    emit_scalar(out, "dblquad_var", d2)
    # tplquad: ∫_0^1 ∫_0^2 ∫_0^3 x*y*z dz dy dx ; func(z, y, x)
    t1 = spi.tplquad(lambda z, y, x: x * y * z, 0, 1, lambda x: 0, lambda x: 2,
                     lambda x, y: 0, lambda x, y: 3)[0]
    emit_scalar(out, "tplquad_xyz", t1)
    # nquad: ∫∫∫ over [0,1]x[0,2]x[0,3] of x0*x1*x2
    nq = spi.nquad(lambda x0, x1, x2: x0 * x1 * x2, [[0, 1], [0, 2], [0, 3]])[0]
    emit_scalar(out, "nquad_3d", nq)

    # ---- two-point boundary value problems: solve_bvp ----
    # Problem (a): y'' = -y as y0'=y1, y1'=-y0 on [0, pi/2], bc y0(0)=0, y0(pi/2)=1.
    # Analytic: y0 = sin x, y1 = cos x.
    xa = np.linspace(0.0, np.pi / 2.0, 11)
    emit_vec("bvp_sin_x", xa)
    emit_vec("bvp_sin_y0", np.sin(xa))
    emit_vec("bvp_sin_y1", np.cos(xa))
    sa = spi.solve_bvp(lambda x, y: np.vstack([y[1], -y[0]]),
                       lambda ya, yb: np.array([ya[0], yb[0] - 1.0]),
                       xa, np.vstack([np.zeros_like(xa), np.ones_like(xa)]))
    emit_mat(out, "bvp_sin_scipy", sa.sol(xa))  # shape (2, 11)
    # Problem (b): y'' = 6x as y0'=y1, y1'=6x on [0, 1], bc y0(0)=0, y0(1)=1.
    # Analytic: y0 = x^3, y1 = 3 x^2.
    xb = np.linspace(0.0, 1.0, 11)
    emit_vec("bvp_cubic_x", xb)
    emit_vec("bvp_cubic_y0", xb ** 3)
    emit_vec("bvp_cubic_y1", 3.0 * xb ** 2)

    # ---- Airy + elliptic integrals ----
    def emit_vec(name, arr):  # local (mirrors the fft helper)
        arr = np.asarray(arr, dtype=float).ravel()
        out.append(f"inline const double {name}[] = {{{', '.join(fmt(v) for v in arr)}}};")
        out.append(f"inline constexpr int {name}_n = {len(arr)};")

    ax = [-8.0, -5.0, -2.0, -1.0, -0.5, -0.1, 0.0, 0.1, 0.5, 1.0, 2.0, 5.0, 8.0, 10.0]
    emit_vec("ai_x", ax)
    aiv = [sps.airy(x) for x in ax]
    emit_vec("ai_Ai", [v[0] for v in aiv])
    emit_vec("ai_Aip", [v[1] for v in aiv])
    emit_vec("ai_Bi", [v[2] for v in aiv])
    emit_vec("ai_Bip", [v[3] for v in aiv])
    aex = [-8.0, -2.0, -0.5, 0.0, 0.5, 2.0, 5.0, 8.0, 10.0, 12.0]
    emit_vec("aie_x", aex)
    aiev = [sps.airye(x) for x in aex]
    emit_vec("aie_Ai", [v[0] for v in aiev])
    emit_vec("aie_Aip", [v[1] for v in aiev])
    emit_vec("aie_Bi", [v[2] for v in aiev])
    emit_vec("aie_Bip", [v[3] for v in aiev])

    em = [-2.0, -1.0, -0.5, 0.0, 0.25, 0.5, 0.75, 0.9, 0.99]
    emit_arr(out, "ellipk", em, sps.ellipk)
    emit_arr(out, "ellipe", em, sps.ellipe)
    ep = [1e-3, 0.01, 0.1, 0.25, 0.5, 0.9, 1.0]
    emit_arr(out, "ellipkm1", ep, sps.ellipkm1)
    # incomplete F(phi|m), E(phi|m): grids over (phi, m), including phi > pi/2
    eiphi = [0.0, 0.3, 0.7, 1.0, 1.5, 2.0, 3.0, -0.5, -2.0]
    for tag, mm in [("a", 0.3), ("b", 0.6), ("c", 0.9)]:
        emit_vec(f"eiF_{tag}_phi", eiphi)
        emit_vec(f"eiF_{tag}_out", [sps.ellipkinc(p, mm) for p in eiphi])
        emit_vec(f"eiE_{tag}_out", [sps.ellipeinc(p, mm) for p in eiphi])
        emit_scalar(out, f"ei_m_{tag}", mm)
    # Jacobi elliptic functions: grids over (u, m)
    eju = [0.0, 0.5, 1.0, 1.5, 2.5, 3.0, -1.0, -2.0]
    for tag, mm in [("a", 0.3), ("b", 0.6), ("c", 0.9)]:
        ejv = [sps.ellipj(u, mm) for u in eju]
        emit_vec(f"ej_{tag}_u", eju)
        emit_vec(f"ej_{tag}_sn", [v[0] for v in ejv])
        emit_vec(f"ej_{tag}_cn", [v[1] for v in ejv])
        emit_vec(f"ej_{tag}_dn", [v[2] for v in ejv])
        emit_vec(f"ej_{tag}_ph", [v[3] for v in ejv])
        emit_scalar(out, f"ej_m_{tag}", mm)

    # ---- error-function relatives ----
    erfcx_x = [-25.0, -10.0, -5.0, -2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0, 5.0,
               10.0, 24.0, 25.0, 26.0, 30.0, 50.0, 100.0, 1000.0, 1e6]
    emit_arr(out, "erfcx", erfcx_x, sps.erfcx)
    dawsn_x = [-50.0, -10.0, -6.0, -5.0, -4.0, -3.5, -3.0, -2.0, -1.0, -0.5,
               -0.2, -0.1, 0.0, 0.1, 0.2, 0.5, 1.0, 2.0, 3.0, 3.5, 4.0, 5.0,
               6.0, 10.0, 50.0, 1000.0]
    emit_arr(out, "dawsn", dawsn_x, sps.dawsn)
    # fresnel S, C
    fr_x = [-8.0, -5.0, -3.0, -2.0, -1.5, -1.0, -0.5, 0.0, 0.3, 0.7, 1.0, 1.5,
            2.0, 2.5, 3.0, 4.0, 5.0, 8.0]
    emit_vec("fr_x", fr_x)
    frv = [sps.fresnel(x) for x in fr_x]
    emit_vec("fr_S", [v[0] for v in frv])
    emit_vec("fr_C", [v[1] for v in frv])
    # voigt_profile over x for several (sigma, gamma) including gamma = 0
    vt_x = [0.0, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 12.0]
    emit_vec("vt_x", vt_x)
    for tag, (sg, gm) in [("a", (1.0, 0.5)), ("b", (2.0, 0.1)), ("c", (0.5, 1.0)),
                          ("d", (1.5, 0.0)), ("e", (3.0, 2.0))]:
        emit_vec(f"vt_{tag}", [sps.voigt_profile(x, sg, gm) for x in vt_x])
        emit_scalar(out, f"vt_{tag}_sigma", sg)
        emit_scalar(out, f"vt_{tag}_gamma", gm)
    # wofz at complex points (upper half-plane; includes negative real part)
    wz = [(0.5, 0.5), (1.0, 1.0), (2.0, 1.0), (1.0, 2.0), (3.0, 2.0), (0.3, 1.0),
          (5.0, 0.5), (0.0, 1.0), (0.0, 3.0), (2.0, 0.1), (4.0, 0.5),
          (-2.0, 1.0), (-1.0, 0.3)]
    emit_vec("wz_re", [p[0] for p in wz])
    emit_vec("wz_im", [p[1] for p in wz])
    wzv = [sps.wofz(complex(p[0], p[1])) for p in wz]
    emit_vec("wz_wre", [v.real for v in wzv])
    emit_vec("wz_wim", [v.imag for v in wzv])

    # ---- spherical Bessel functions (integer order n = 0..4) ----
    sbx = [-8.0, -5.0, -2.0, -1.0, -0.5, 0.5, 1.0, 2.0, 5.0, 8.0]
    emit_vec("sb_x", sbx)
    for n in range(5):
        emit_vec(f"sb_jn{n}", [sps.spherical_jn(n, x) for x in sbx])
        emit_vec(f"sb_yn{n}", [sps.spherical_yn(n, x) for x in sbx])
        emit_vec(f"sb_in{n}", [sps.spherical_in(n, x) for x in sbx])
        emit_vec(f"sb_kn{n}", [sps.spherical_kn(n, x) for x in sbx])

    # ---- sine/cosine integrals sici(x) -> (Si, Ci) ----
    # grid avoids the 16..24 transition gap where neither the convergent series
    # nor the asymptotic expansion reaches full double precision.
    sci_x = [0.5, 1.0, 2.0, 3.0, 4.0, 6.0, 8.0, 10.0, 14.0, 25.0, 50.0,
             -3.0, -8.0, -25.0]
    emit_vec("sci_x", sci_x)
    scv_ = [sps.sici(x) for x in sci_x]
    emit_vec("sci_Si", [v[0] for v in scv_])
    emit_vec("sci_Ci", [v[1] for v in scv_])
    # hyperbolic sine/cosine integrals shichi(x) -> (Shi, Chi)
    shi_x = [0.1, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 12.0, 20.0, -3.0, -8.0]
    emit_vec("shi_x", shi_x)
    shv_ = [sps.shichi(x) for x in shi_x]
    emit_vec("shi_Shi", [v[0] for v in shv_])
    emit_vec("shi_Chi", [v[1] for v in shv_])

    # ---- misc: lambertw / zeta / zetac / struve / modstruve / spence ----
    # Lambert W principal branch (k=0), x >= -1/e; compare SciPy's real part.
    lw0_x = [-0.36, -0.3, -0.2, -0.1, 1e-3, 0.5, 1.0, 2.0, 5.0, 10.0, 100.0, 1000.0]
    emit_vec("lw0_x", lw0_x)
    emit_vec("lw0", [sps.lambertw(x, 0).real for x in lw0_x])
    # Lambert W k=-1 branch, on [-1/e, 0).
    lwm1_x = [-0.36, -0.3, -0.2, -0.1, -0.05, -0.01, -1e-3, -1e-6]
    emit_vec("lwm1_x", lwm1_x)
    emit_vec("lwm1", [sps.lambertw(x, -1).real for x in lwm1_x])
    # Riemann zeta and zetac on the real line (avoid the pole at x = 1).
    zeta_x = [-3.0, -2.0, -1.0, -0.5, 0.0, 0.25, 0.5, 0.999, 1.001,
              1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 7.0, 10.0, 15.0]
    emit_vec("zeta_x", zeta_x)
    emit_vec("zeta_v", [sps.zeta(x) for x in zeta_x])
    emit_vec("zetac_v", [sps.zetac(x) for x in zeta_x])
    # Struve H_v and modified Struve L_v: grids stay out of the 13..18 band where
    # the alternating series cancels before the asymptotic series converges.
    struve_x = [0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 10.0, 25.0, 30.0, 50.0]
    emit_vec("struve_x", struve_x)
    for v in (0, 1, 2):
        emit_vec(f"struve_h{v}", [sps.struve(v, x) for x in struve_x])
    emit_vec("struve_hhalf", [sps.struve(0.5, x) for x in struve_x])
    mstruve_x = [0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 10.0, 16.0, 20.0]
    emit_vec("mstruve_x", mstruve_x)
    for v in (0, 1, 2):
        emit_vec(f"mstruve_l{v}", [sps.modstruve(v, x) for x in mstruve_x])
    emit_vec("mstruve_lhalf", [sps.modstruve(0.5, x) for x in mstruve_x])
    # Spence's dilogarithm Li_2(1 - x), x >= 0.
    emit_arr(out, "spence", [0.0, 0.1, 0.3, 0.5, 0.8, 1.0, 1.2, 1.5, 2.0, 3.0,
                             5.0, 10.0, 50.0, 100.0], sps.spence)

    # ---- hypergeometric functions ----
    # hyp0f1(b, x): confluent 0F1 limit on a moderate grid.
    h0f1_x = [-4.0, -2.0, -0.5, 0.3, 1.0, 2.0, 4.0, 8.0]
    emit_vec("h0f1_x", h0f1_x)
    emit_vec("h0f1_b2", [sps.hyp0f1(2.0, x) for x in h0f1_x])
    emit_vec("h0f1_bhalf", [sps.hyp0f1(0.5, x) for x in h0f1_x])
    # hyp1f1(a, b, x) = M(a,b,x): both signs of x (Kummer transform path).
    h1f1_x = [-5.0, -3.0, -1.0, -0.5, 0.5, 1.0, 2.0, 4.0, 6.0]
    emit_vec("h1f1_x", h1f1_x)
    emit_vec("h1f1_a", [sps.hyp1f1(1.5, 2.5, x) for x in h1f1_x])
    emit_vec("h1f1_b", [sps.hyp1f1(-2.0, 3.0, x) for x in h1f1_x])  # polynomial case
    emit_vec("h1f1_c", [sps.hyp1f1(0.5, 1.3, x) for x in h1f1_x])
    # hyp2f1(a, b, c, z): direct series, Pfaff (z<0) and 1-z reflection (z->1).
    h2f1_z = [-0.9, -0.6, -0.3, 0.0, 0.3, 0.5, 0.7, 0.85, 0.95]
    emit_vec("h2f1_z", h2f1_z)
    emit_vec("h2f1_a", [sps.hyp2f1(0.5, 1.0, 1.5, z) for z in h2f1_z])
    emit_vec("h2f1_b", [sps.hyp2f1(1.0, 2.0, 3.5, z) for z in h2f1_z])
    emit_vec("h2f1_c", [sps.hyp2f1(-1.5, 0.7, 2.2, z) for z in h2f1_z])
    emit_scalar(out, "h2f1_one", sps.hyp2f1(0.5, 1.0, 3.0, 1.0))  # Gauss theorem
    # hyperu(a, b, x): Tricomi U for x>0, non-integer b.
    hu_x = [0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0]
    emit_vec("hu_x", hu_x)
    emit_vec("hu_a", [sps.hyperu(0.5, 1.3, x) for x in hu_x])
    emit_vec("hu_b", [sps.hyperu(2.0, 0.4, x) for x in hu_x])
    emit_vec("hu_c", [sps.hyperu(1.5, 2.7, x) for x in hu_x])

    # ---- odr (orthogonal distance regression) ----
    import scipy.odr as sodr

    def emit_vec_odr(name, arr):
        arr = np.asarray(arr, dtype=float).ravel()
        out.append(f"inline const double {name}[] = {{{', '.join(fmt(v) for v in arr)}}};")
        out.append(f"inline constexpr int {name}_n = {len(arr)};")

    def _odr_lin(B, xx):
        return B[0] + B[1] * xx

    def _odr_exp(B, xx):
        return B[0] * np.exp(B[1] * xx)

    # (a) linear model y = b0 + b1 x with noise in both variables.
    rng = np.random.RandomState(0)
    xl = np.linspace(0, 10, 15)
    yl_true = 2.0 + 1.5 * xl
    xl = xl + rng.normal(0, 0.1, xl.size)
    yl = yl_true + rng.normal(0, 0.2, xl.size)
    emit_vec_odr("odr_lin_x", xl)
    emit_vec_odr("odr_lin_y", yl)
    ol = sodr.ODR(sodr.Data(xl, yl), sodr.Model(_odr_lin), beta0=[1.0, 1.0]).run()
    emit_vec_odr("odr_lin_beta", ol.beta)
    emit_vec_odr("odr_lin_sdbeta", ol.sd_beta)
    emit_scalar(out, "odr_lin_resvar", ol.res_var)
    emit_scalar(out, "odr_lin_ss", ol.sum_square)

    # (b) nonlinear model y = b0 * exp(b1 x).
    rng = np.random.RandomState(3)
    xn_ = np.linspace(0, 2, 12)
    yn_true = 2.5 * np.exp(0.7 * xn_)
    xn_ = xn_ + rng.normal(0, 0.02, xn_.size)
    yn_ = yn_true + rng.normal(0, 0.1, xn_.size)
    emit_vec_odr("odr_nl_x", xn_)
    emit_vec_odr("odr_nl_y", yn_)
    on = sodr.ODR(sodr.Data(xn_, yn_), sodr.Model(_odr_exp), beta0=[1.0, 1.0]).run()
    emit_vec_odr("odr_nl_beta", on.beta)
    emit_vec_odr("odr_nl_sdbeta", on.sd_beta)
    emit_scalar(out, "odr_nl_resvar", on.res_var)
    emit_scalar(out, "odr_nl_ss", on.sum_square)

    # (c) weighted linear model with per-point standard deviations sx, sy.
    rng = np.random.RandomState(5)
    xw = np.linspace(0, 10, 12)
    yw_true = 1.0 + 0.8 * xw
    sxw = np.full(xw.size, 0.1)
    syw = np.full(xw.size, 0.3)
    xw = xw + rng.normal(0, 0.1, xw.size)
    yw = yw_true + rng.normal(0, 0.3, xw.size)
    emit_vec_odr("odr_w_x", xw)
    emit_vec_odr("odr_w_y", yw)
    emit_vec_odr("odr_w_sx", sxw)
    emit_vec_odr("odr_w_sy", syw)
    ow = sodr.ODR(sodr.Data(xw, yw, wd=1.0 / sxw**2, we=1.0 / syw**2),
                  sodr.Model(_odr_lin), beta0=[0.0, 1.0]).run()
    emit_vec_odr("odr_w_beta", ow.beta)
    emit_vec_odr("odr_w_sdbeta", ow.sd_beta)
    emit_scalar(out, "odr_w_resvar", ow.res_var)
    emit_scalar(out, "odr_w_ss", ow.sum_square)

    out.append("}  // namespace golden")
    os.makedirs(os.path.dirname(GOLDEN), exist_ok=True)
    with open(GOLDEN, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", GOLDEN)

    # ---- CODATA table ----
    lines = ["// AUTO-GENERATED by tests/oracle/generate.py from scipy.constants. Do not edit."]
    for key in sorted(spc.physical_constants):
        v, u, unc = spc.physical_constants[key]
        ek = key.replace("\\", "\\\\").replace('"', '\\"')
        eu = u.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{{"{ek}", {{{fmt(v)}, "{eu}", {fmt(unc)}}}}},')
    with open(CODATA, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", CODATA, f"({len(spc.physical_constants)} entries)")


if __name__ == "__main__":
    main()
